name: Deploy PetTake

on:
  push:
    branches: [master]

jobs:
  deploy-ui:
    name: Deploy React UI to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          cd ui/
          npm ci
          npm run build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ui/build

  deploy-api:
    name: Deploy Express API to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'pettake'
          heroku_email: 'yosep.ryan.yra@gmail.com'
